import localFont from 'next/font/local';
import type { Metadata } from "next";
import "./globals.css";

const ttCommonsRegular = localFont({
  src: '../../public/fonts/TT-COMMONS/TTCommons-Regular.ttf',
  variable: '--font-tt-commons-regular',
});

const ttCommonsMedium = localFont({
  src: '../../public/fonts/TT-COMMONS/TTCommons-Medium.ttf',
  variable: '--font-tt-commons-medium',
});

const ttCommonsDemiBold = localFont({
  src: '../../public/fonts/TT-COMMONS/TTCommons-DemiBold.ttf',
  variable: '--font-tt-commons-demibold',
});

const publicoHeadlineBold = localFont({
  src: '../../public/fonts/Publico-Headline-Web/Publico Headline Web Bold.ttf',
  variable: '--font-publico-headline-bold',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`
          ${ttCommonsRegular.className} 
          ${ttCommonsMedium.variable} 
          ${ttCommonsDemiBold.variable} 
          ${publicoHeadlineBold.variable}
        `}>
        {children}
      </body>
    </html>
  );
}
